### ISSUE TITLE
Sites link to?

### ISSUE THREAD

**Issue by danaskallman** [meitar/multisite-directory#11]
Are the sites listed here: https://cosecha.dev.glocal.coop/blog/network_directory/ supposed to link off to the website? When I click on them, it just keeps me on that page. Let me know if I'm missing something.

**Comment by fabacab** [comment]
That I couldn't tell you because I'm not sure how @misfist has set up that particular template. In terms of displaying the directory contents, most of that is intentionally delegated to the theme that's in use. The plugin merely provides the data used by the themes. I think this is actually a Glocal Coop ANP Network Main Theme v2 issue?
