### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by hvianna** [meitar/multisite-directory#20]
First of all, I'm sorry for my PR completely without notice. I'm new to contributing code here on GitHub and still learning the ropes (plus, poor social skills).. Anyway, I have a few more suggestions that were just commited and I just realized they would be included in the original PR, so I decided to open this issue and properly present my suggestions.

So here's a summary of changes proposed in #19 

+ wp_get_sites() is deprecated since 4.6, so it was replaced by get_sites();
+ Category fields are now also displayed in the super-admin add site form (I suppose many networks won't allow users to create new sites themselves);
+ Added action/function to load the plugin's textdomain for translations;
+ Added pt_BR translation;
+ Renamed previous translation files to match the textdomain (I haven't updated the strings though);
+ Added action/function to redirect single site posts to the actual
sites in the network (works great for search results on your network main site);
+ Renamed the admin menu item from 'Sites' to 'Directory', so it won't
get confused with the network admin menu item.

**Comment by fabacab** [comment]
Thank you so much for the pull request. You're 💯% awesome!

For what it's worth, it's perfectly okay with me if you open a pull request *instead* of an issue. I use issues as a sort of "to do list" while pull requests are more useful to me as a showcase of work in progress. Pull requests are also more appropriate in this case than a single issue is because a pull request can contain more than one chunk of behavior (as long as the commits in the pull request are [atomic](https://en.wikipedia.org/wiki/Atomic_commit)), whereas issues that represent more than one distinct issue undermines the utility of using an issue tracker in the first place. ;)

So, with that said, I really like your suggestions and will review them in the pull request itself.
